apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  labels: { app: hello-nginx }
spec:
  replicas: 2        # HPA min
  selector:
    matchLabels: { app: hello-nginx }
  template:
    metadata:
      labels: { app: hello-nginx }
    spec:
      containers:
        - name: nginx
          image: nginx:latest   # <‑ bump this tag to trigger Argo
          ports: [{ containerPort: 80 }]
          resources:
            limits:   { cpu: 250m, memory: 128Mi }
            requests: { cpu: 100m, memory: 64Mi }
