apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
  source:
    repoURL: https://github.com/Ordotan1994/eks.git
    targetRevision: HEAD
    path: apps/hello-nginx
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [ CreateNamespace=true ]
